POST http://localhost:3003/user/signup
Content-Type: application/json

{
 
   "email": "sabrina@sabrina.com" ,
   "password": "123456"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
 
   "email": "sabrina@sabrina.com" ,
   "password": "123456"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5M2Y3MjNhLTFmYTEtNDcyNy1hNDYxLWE1YWVjYjBiODY4NyIsImlhdCI6MTY1NjM2MTQwM30.GdtntMZBuiwHu_N7UqTujsB0Ix9G1D0eTUbNaMw4fhw

GET http://localhost:3003/user/profile
Authorization: {{token}}
