POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Giovana",
   "email": "giovana@hotmail.com" ,
   "password": "12345678",
   "role": "ADMIN"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
 
   "email": "sabrina@sabrina.com" ,
   "password": "poiuytre"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjNzc1MGY1LWJmYjAtNGVkMy1iMWNiLWE5ZmIwYzdmMjRjNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTY1MTEzNTJ9.3eHrouivpxPcN2zDuAnF29DcXykSQuoxqpZt4qeC5y0

GET http://localhost:3003/user/profile
Authorization: {{token}}

###
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: {{token}}

{
   "title": "",
   "description": "Unte uma pedra de mármore ou uma assadeira com um pouco de óleo. Misture em uma panela o coco, o leite condensado e o açúcar. Leve ao fogo e misture bem, cozinhe misturando regularmente com uma colher de pau. Quando o doce começar a ser soltar do fundo da panela, retire do fogo e acrescente a manteiga. Bata bem com a colher de pau para que o doce açucare. Despeje sobre o mármore untado e deixe esfriar. Corte quadrados de 10 x 10 cm."
}

###

GET http://localhost:3003/user/profile/b7565e42-0cd3-4fbf-b915-fdffc85c511e
Authorization: {{token}}

###

GET http://localhost:3003/recipe/144fd345-8ccf-40c2-8c78-4799e8004ea1
Authorization: {{token}}